# Generated by Django 5.2.8 on 2025-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSuggection',
            fields=[
                ('suggectid', models.AutoField(db_column='suggectID', primary_key=True, serialize=False)),
                ('categoryID', models.IntegerField(blank=True, db_column='CategoryID', null=True)),
                ('userID', models.CharField(blank=True, db_column='userID', max_length=45, null=True)),
                ('aiRecommedGuideline', models.CharField(blank=True, db_column='aiRecommedGuideline', max_length=1000, null=True)),
                ('expectedResults', models.CharField(blank=True, db_column='expectedResults', max_length=1000, null=True)),
                ('suggestDate', models.DateTimeField(blank=True, db_column='suggestDate', null=True)),
            ],
            options={
                'db_table': 'ai_suggection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaignid', models.IntegerField(db_column='campaignID', primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(blank=True, db_column='customerID', null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('givetime', models.DateTimeField(blank=True, db_column='giveTime', null=True)),
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('isuse', models.CharField(blank=True, db_column='isUse', max_length=10, null=True)),
            ],
            options={
                'db_table': 'campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('chatID', models.AutoField(db_column='chatID', primary_key=True, serialize=False)),
                ('categoryID', models.IntegerField(blank=True, db_column='categoryID', null=True)),
                ('userContent', models.TextField(blank=True, db_column='userContent', null=True)),
                ('aiContent', models.TextField(blank=True, db_column='aiContent', null=True)),
            ],
            options={
                'db_table': 'chat_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(db_column='customerID', primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='customerName', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=10, null=True)),
                ('customerbirth', models.DateField(blank=True, db_column='customerBirth', null=True)),
                ('customerregion', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', db_column='customerRegion', max_length=100, null=True)),
                ('customerjoinday', models.DateField(blank=True, db_column='customerJoinDay', null=True)),
                ('categoryid', models.CharField(blank=True, db_column='categoryID', max_length=10, null=True)),
                ('customerlastdaybuy', models.DateField(blank=True, db_column='customerLastDayBuy', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('customercategory', models.CharField(blank=True, db_column='customerCategory', max_length=45, null=True)),
            ],
            options={
                'db_table': 'customer_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.IntegerField(db_column='productID', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=100, null=True)),
                ('productprice', models.FloatField(blank=True, db_column='productPrice', null=True)),
                ('categoryid', models.CharField(blank=True, db_column='categoryID', max_length=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('statue', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='categoryName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'product_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RFMscore',
            fields=[
                ('customerID', models.IntegerField(db_column='customerID', primary_key=True, serialize=False)),
                ('rScore', models.IntegerField(blank=True, db_column='rScore', null=True)),
                ('fScore', models.IntegerField(blank=True, db_column='fScore', null=True)),
                ('mScore', models.IntegerField(blank=True, db_column='mScore', null=True)),
                ('RFMscore', models.IntegerField(blank=True, db_column='RFMscore', null=True)),
                ('categoryID', models.IntegerField(blank=True, db_column='categoryID', null=True)),
                ('RFMupdate', models.DateTimeField(blank=True, db_column='RFMupdate', null=True)),
            ],
            options={
                'db_table': 'rfm_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.IntegerField(db_column='transactionID', primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(blank=True, db_column='customerID', null=True)),
                ('transdate', models.DateField(blank=True, db_column='transDate', null=True)),
                ('totalprice', models.FloatField(blank=True, db_column='totalPrice', null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='userName', max_length=45, null=True)),
                ('employeeid', models.IntegerField(blank=True, db_column='employeeID', null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
